name: craftbeer
description: The brewer app for excelence.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 1.0.3

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  #View logic
  provider: ^4.1.2
  # Authentication
  #firebase_auth: ^0.16.0
  #google_sign_in: ^4.4.6
  #UI Utilities
  flare_splash_screen: ^3.0.1
  fluttertoast: ^4.0.1
  story_view: ^0.12.3
  flutter_typeahead: ^1.8.0
  url_launcher: ^5.4.7
  flutter_staggered_grid_view: ^0.3.0
  #Storage
  cloud_firestore: ^0.13.5
  sqflite: ^1.3.0+1
  cached_network_image: ^2.2.0+1
  shared_preferences: ^0.5.7+2
  #Network
  http: ^0.12.1
  firebase_messaging: ^6.0.15
  connectivity: ^0.4.8+6
  #Maps
  google_maps_flutter: ^0.5.28+1
  webview_flutter: ^0.3.22+1
  firebase_crashlytics: ^0.1.3+3
  permission_handler: ^5.0.0+hotfix.8
  flutter_cache_manager: ^1.4.1

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family:  BeerIcon
      fonts:
        - asset: fonts/BeerIcon.ttf
    - family: FellGreat
      fonts:
        - asset: fonts/IMFellGreatPrimer-Regular.ttf
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
flutter_intl:
  enabled: true
